/**
 * Regenerates src/apps/deadlines/world-map.generated.ts from Natural Earth 110m country
 * outlines. Run with `npx tsx scripts/generate-world-map.ts` when the outlines need refreshing;
 * the generated file is committed so the app has no runtime map dependency.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const SOURCE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson";
const OUT = join(process.cwd(), "src/apps/deadlines/world-map.generated.ts");

// Equirectangular projection cropped to the inhabited latitudes (Antarctica is dropped).
const WIDTH = 1000;
const NORTH = 84;
const SOUTH = -60;
const HEIGHT = ((NORTH - SOUTH) / 360) * WIDTH;

type Ring = [number, number][];
type Geometry = { type: "Polygon"; coordinates: Ring[] } | { type: "MultiPolygon"; coordinates: Ring[][] };
type Feature = { properties: Record<string, string>; geometry: Geometry | null };

const project = ([lon, lat]: [number, number]): [number, number] => [
  Math.round(((lon + 180) / 360) * WIDTH * 10) / 10,
  Math.round(((NORTH - Math.max(Math.min(lat, NORTH), SOUTH)) / 360) * WIDTH * 10) / 10,
];

/** Screen-space area of a ring, used to drop specks that render as a single pixel. */
function area(ring: [number, number][]): number {
  let sum = 0;
  for (let i = 0; i < ring.length; i++) {
    const [x1, y1] = ring[i];
    const [x2, y2] = ring[(i + 1) % ring.length];
    sum += x1 * y2 - x2 * y1;
  }
  return Math.abs(sum) / 2;
}

function ringPath(ring: Ring): string | null {
  const points: [number, number][] = [];
  for (const coord of ring) {
    const point = project(coord);
    const last = points[points.length - 1];
    if (!last || last[0] !== point[0] || last[1] !== point[1]) points.push(point);
  }
  if (points.length < 3 || area(points) < 0.6) return null;
  return `M${points.map(([x, y]) => `${x} ${y}`).join("L")}Z`;
}

function featurePath(geometry: Geometry): string {
  const polygons = geometry.type === "Polygon" ? [geometry.coordinates] : geometry.coordinates;
  return polygons
    .flatMap((rings) => rings.map(ringPath))
    .filter((d): d is string => d !== null)
    .join("");
}

async function main() {
  const response = await fetch(SOURCE);
  if (!response.ok) throw new Error(`Failed to fetch outlines: ${response.status}`);
  const { features } = (await response.json()) as { features: Feature[] };

  const paths = new Map<string, string>();
  for (const feature of features) {
    const code = feature.properties.ISO_A2_EH ?? feature.properties.ISO_A2;
    if (!feature.geometry || !code || code === "-99" || code === "AQ") continue;
    const d = featurePath(feature.geometry);
    if (d) paths.set(code, (paths.get(code) ?? "") + d);
  }

  const entries = [...paths].sort(([a], [b]) => a.localeCompare(b));
  writeFileSync(
    OUT,
    [
      "// Generated by scripts/generate-world-map.ts from Natural Earth 110m data (public domain).",
      "// Equirectangular projection, latitudes cropped to 84N..60S. Do not edit by hand.",
      `export const MAP_WIDTH = ${WIDTH};`,
      `export const MAP_HEIGHT = ${Math.round(HEIGHT)};`,
      `export const MAP_NORTH = ${NORTH};`,
      "",
      "export const COUNTRY_PATHS: Record<string, string> = {",
      ...entries.map(([code, d]) => `  ${code}: ${JSON.stringify(d)},`),
      "};",
      "",
    ].join("\n"),
  );
  console.log(`Wrote ${entries.length} country outlines to ${OUT}`);
}

main();
